apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: products-api
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
    - cloudshop-prod
  selector:
    matchLabels:
      app: products-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
