apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: cloudshop-prod
  labels:
    app: orders-api
spec:
  type: ClusterIP
  selector:
    app: orders-api
  ports:
  - name: http
    port: 8083
    targetPort: 8083
